# Generated by Django 4.2.10 on 2024-03-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('rank', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=200)),
                ('classic_rank', models.PositiveIntegerField()),
                ('rapid_rank', models.PositiveIntegerField()),
                ('blitz_rank', models.PositiveIntegerField()),
            ],
        ),
    ]
