# Generated by Django 4.2.10 on 2024-03-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_player', models.CharField(max_length=100)),
                ('w_player_rank', models.CharField(max_length=100)),
                ('b_player', models.CharField(max_length=100)),
                ('b_player_rank', models.CharField(max_length=100)),
                ('game_result', models.CharField(max_length=100)),
                ('number_of_moves', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lname',
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='blitz_rank',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='classic_rank',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='rapid_rank',
            field=models.CharField(max_length=100),
        ),
    ]
