# Generated by Django 4.2.10 on 2024-03-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_alter_games_w_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
